language: php

php:
  - 7.1

services:
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -e 'create database travis_test;'
  - composer self-update
  - composer install --no-interaction
  - npm install
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit

